### ISSUE TITLE
System is frozen? No confirm_vote for delegator

### ISSUE THREAD

**Issue by lukmarcus** [noisy-witness/steem-wise-voter-page#15]
Wise doesn't work? Votes are not coming out from delegator but there are `send_voteorder` from voters. Examples:

https://steemd.com/tx/3e584c2006bf2b5d832fea06afd99b20f6042f2a
https://steemd.com/tx/e2f05b26ca3f57bed3e6e0079e4e083c22ad1196
https://steemd.com/tx/d372da983a1a3afad6ebaec1162091067a8f03be

**Comment by noisy** [comment]
Thank you for reporting this.

It looks like, lack of response from @noisy account was caused by https://github.com/noisy-witness/steem-wise-cli/issues/8.

if `voteorder` was written into a blockchain, with a message like this:

    [
        "v2:send_voteorder",
        {
            "delegator":"noisy",
            "ruleset":"Na wsparcie tagu #tematygodnia",
            "author":"steemit-polska",
            "permlink":"tematy-tygodnia-tematygodnia-33-wyniki",
            "weight":4955
        }
    ]

then that means that probably this is not a problem with Voter Page, and therefore I will close this issue in this repository. More info will be posted in https://github.com/noisy-witness/steem-wise-cli/issues/8
